name: vault
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault

    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    entrypoint: vault server -config=/vault/config/vault.json
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config

    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    restart: always
