name: vault
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault

    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      # - VAULT_API_ADDR=http://127.0.0.1:8200
      # - VAULT_LOG_LEVEL=debug
    entrypoint: vault server -config=/vault/config/vault.json
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config

    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

    networks:
      - vault-net
    hostname: vault.docker.internal

networks:
  vault-net:
    name: vault-net
