# Justfile

# Variables
# EXAMPLE_VAR := "example"

# List 📜 all recipes (default)
help:
    @just --list

# Start Vault 🔐 and detach 🫥
start-vault:
    @docker compose -f compose.yaml up --detach

# Start Vault 🔐 and stay attached
start-vault-attached:
    @docker compose -f compose.yaml up

# Start Vault 🔐 and detach 🫥
stop-vault:
    @docker compose -f compose.yaml down

# Get the Vault root token and unseal keys (⚠️ save them, as can it be executed only once!)
init-vault:
    #@-VAULT_ADDR='http://127.0.0.1:8200' vault operator init
    @-docker exec -it vault vault operator init

# Unseal the Vault
unseal-vault:
    @echo "\n🔒 Unseal Vault - step 1/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔒 Unseal Vault - step 2/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔒 Unseal Vault - step 3/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔓 Now login to Vault"
    @-docker exec -it vault vault login
    @echo "\n🔑 Vault status"
    @-docker exec -it vault vault status
