# Justfile

# Variables
# EXAMPLE_VAR := "example"

# List 📜 all recipes (default)
help:
    @just --list

# Start Vault 🔐 and detach 🫥
vault-start:
    @docker compose -f compose.yaml up --detach

alias start := vault-start

# Start Vault 🔐 and stay attached to the console/logs
vault-start-attached:
    @docker compose -f compose.yaml up

# Start Vault 🔐 and detach 🫥
vault-stop:
    @docker compose -f compose.yaml down

alias stop := vault-stop

# Get the Vault root token and unseal keys (⚠️ save them, as can it be executed only once!)
vault-init:
    #@-VAULT_ADDR='http://127.0.0.1:8200' vault operator init
    @-docker exec -it vault vault operator init

# Unseal the Vault
vault-unseal:
    @echo "\n🔒 Unseal Vault - step 1/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔒 Unseal Vault - step 2/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔒 Unseal Vault - step 3/3"
    @-docker exec -it vault vault operator unseal
    @echo "\n🔓 Now login to Vault"
    @-docker exec -it vault vault login
    @echo "\n🔑 Vault status"
    @-docker exec -it vault vault status

alias unseal := vault-unseal

# vault logs
vault-logs:
    @tail -f volumes/logs/vault.log

alias logs := vault-logs
