apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: act-runner-root
  name: act-runner-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-runner-root
  strategy: {}
  template:
    metadata:
      labels:
        app: act-runner-root
    spec:
      restartPolicy: Always
      volumes:
      - name: runner-data
        persistentVolumeClaim:
          claimName: act-runner-root-vol
      - name: docker-certs
        emptyDir: {}
      containers:
      - name: runner
        image: gitea/act_runner:nightly
        imagePullPolicy: Always
        # command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- /opt/act/run.sh"]
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
          # value: unix:///var/run/docker.sock
          # value: unix:///run/user/1000/docker.sock
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: GITEA_INSTANCE_URL
          value: http://gitea-http.git.svc.cluster.local:3000
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          value: "FX5UApUIkhLADgRnB04ti7cYNftICkW6HXM0bZz1"
          # valueFrom:
          #   secretKeyRef:
          #     name: runner-secret
          #     key: token
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        - name: runner-data
          mountPath: /data
        resources: {}
            # limits:
            #   memory: "512Mi"
            #   cpu: "500m"
            # requests:
            #   memory: "256Mi"
            #   cpu: "250m"
      - name: daemon
        image: docker:26-dind
        # image: docker:23.0.6-dind
        # check: https://hub.docker.com/_/docker/tags?name=dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        resources: {}
            # limits:
            #   memory: "512Mi"
            #   cpu: "500m"
            # requests:
            #   memory: "256Mi"
            #   cpu: "250m"
