---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: act-runner-rootless-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: act-runner-root-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
