project: act-runners

# Set this if you want to carry over parent process' environment variables
# carry_env: true

# Providers
providers:
  hashicorp_vault:
    env_sync:
      path: secret/data/gitea/runner-registration-token
