# Customized Act Runner with root user for Docker-in-Docker
name: act-runner-nuvola
services:
  act-runner-nuvola-1:
    container_name: act-runner-nuvola-1

    image: ghcr.io/kubernetista/act-runner-nuvola:latest

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://git.localtest.me/"
      GITEA_RUNNER_REGISTRATION_TOKEN: "KxKgUy419jnwAkkaBhu73PqD7VPbN7nhkKuE8eyY"
      GITEA_RUNNER_NAME: "act-runner-docker-1"
      GITEA_RUNNER_LABELS: "docker"

    volumes:
      - ./config.yaml:/config.yaml
      # - ./full-ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - ./data-1:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./run.sh:/opt/act/run.sh
      - ./git.localtest.me.crt:/usr/share/ca-certificates/extra/git.localtest.me.crt

    privileged: true

    # entrypoint: []
    # command: sleep infinity

    network_mode: host
    restart: unless-stopped

  act-runner-nuvola-2:
    container_name: act-runner-nuvola-2
    image: ghcr.io/kubernetista/act-runner-nuvola:latest
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://git.localtest.me/"
      GITEA_RUNNER_REGISTRATION_TOKEN: "KxKgUy419jnwAkkaBhu73PqD7VPbN7nhkKuE8eyY"
      GITEA_RUNNER_NAME: "act-runner-docker-2"
      GITEA_RUNNER_LABELS: "docker"
    volumes:
      - ./config.yaml:/config.yaml
      - ./data-2:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./run.sh:/opt/act/run.sh
      - ./git.localtest.me.crt:/usr/share/ca-certificates/extra/git.localtest.me.crt
    privileged: true
    network_mode: host
    restart: unless-stopped
