# Customized Act Runner with root user, Docker-in-Docker
name: act-runner-nuvola

# Shared environment configuration using YAML anchor
x-common-env: &common-env
  GITEA_HOSTNAME: ${GITEA_HOSTNAME}
  # GITEA_INSTANCE_URL: "https://${GITEA_HOSTNAME}/"
  # Secrets from teller
  GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
  # Other required env vars with defaults
  CONFIG_FILE: ${CONFIG_FILE:-/config.yaml}
  GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL:-https://${GITEA_HOSTNAME}/}
  GITEA_RUNNER_LABELS: ${GITEA_RUNNER_LABELS:-docker}


services:
  act-runner-nuvola-1:
    container_name: act-runner-nuvola-1
    image: ghcr.io/kubernetista/act-runner-nuvola:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Merge shared env
      <<: *common-env
      GITEA_RUNNER_NAME: "act-runner-docker-1"
    volumes:
      - ./data-1:/data
      - ./${GITEA_HOSTNAME}.crt:/usr/share/ca-certificates/extra/${GITEA_HOSTNAME}.crt
      - ./config.yaml:/config.yaml
      - ./run.sh:/opt/act/run.sh
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    # entrypoint: []
    # command: sleep infinity
    network_mode: host
    restart: unless-stopped

  act-runner-nuvola-2:
    container_name: act-runner-nuvola-2
    image: ghcr.io/kubernetista/act-runner-nuvola:latest
    environment:
      # Merge shared env
      <<: *common-env
      GITEA_RUNNER_NAME: "act-runner-docker-2"
    volumes:
      - ./data-2:/data
      - ./${GITEA_HOSTNAME}.crt:/usr/share/ca-certificates/extra/${GITEA_HOSTNAME}.crt
      - ./config.yaml:/config.yaml
      - ./run.sh:/opt/act/run.sh
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    network_mode: host
    restart: unless-stopped
