# Customized Act Runner with root user for Docker-in-Docker
name: act-runner-root
services:
  act-runner-root:
    container_name: act-runner-root

    # image: ghcr.io/kubernetista/runner-root:v2
    # image: act-runner-root:v20241112
    image: act-runner-root:latest

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - REGISTRY_GITEA_HTTPS=git.localhost:8443
      - REGISTRY_USERNAME=aruba-demo
      - REGISTRY_PASSWORD=NeOzersChqN9fydl

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./full-ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt

    privileged: true
    command: sleep infinity
    network_mode: host
    restart: unless-stopped
