# Create this secret with your Vault root token
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
data:
  # Temporary token (240h) for Vault
  token: ${VAULT_TEMPORARY_TOKEN}
