# Create this secret with your Vault root token
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
data:
  # Replace with your base64 encoded Vault token
  token: aHZzLkNBRVNJSlJYbWNZTnpiMGNuS2hiakNwMmhLc2MtQWdfWEROc21HZzVlSW1CMWpkeUdoNEtIR2gyY3k1UVFqQmhSREpMZUdGU01UQmpPWFZKZG1VMlYyOU9iRlE=
