# Create this secret with your Vault root token
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
data:
  # Temporary token (480h, expire 2024-12-17 10:01:38 Z) for Vault
  token: ${VAULT_TEMPORARY_TOKEN}
