apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example-app-postgresql
  namespace: git
spec:
  # instances: 3
  instances: 1

  postgresql:
    parameters: {}
      # timezone: "Europe/Rome"

  bootstrap:
    initdb:
      database: example-app
      owner: example-app # Defaults to the database name
      secret:
        name: example-app-postgresql-user-secret # Name of the secret containing the initial credentials for the owner of the user database. If empty a new secret will be created from scratch
      options: []
      encoding: UTF8
      postInitSQL: []
        # - CREATE EXTENSION IF NOT EXISTS hstore;​
      # postInitApplicationSQL:
        # - |
          # CREATE SCHEMA IF NOT EXISTS example-app
            # AUTHORIZATION postgres;
        # CREATE USER example-app WITH ENCRYPTED PASSWORD 'example-app';
        # GRANT ALL PRIVILEGES ON DATABASE example-app TO example-app;
      postInitTemplateSQL: []

  storage:
    size: 8Gi
    # storageClass: ""
    # TODO: Error without specifying a storage class: understand why
    storageClass: "local-path"

  # -- The instances' log level, one of the following values: error, warning, info (default), debug, trace
  logLevel: "info"

  # -- When this option is enabled, the operator will use the SuperuserSecret to update the postgres user password.
  # If the secret is not present, the operator will automatically create one.
  # When this option is disabled, the operator will ignore the SuperuserSecret content, delete it when automatically created,
  # and then blank the password of the postgres user by setting it to NULL.
  enableSuperuserAccess: true
  # superuserSecret: ""
  superuserSecret:
      name: example-app-postgresql-superuser-secret
