apiVersion: v1
kind: Secret
metadata:
  name: example-app-postgresql-superuser-secret
  namespace: git
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
  # username: Z2l0ZWE=  # base64 encoded
  # password: Z2l0ZWE=  # base64 encoded
