apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls-wildcard-localtest-me
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: tls-wildcard-localtest-me
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: tls/wildcard-localtest-me
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: tls/wildcard-localtest-me
      property: tls.key
