# external-secret-gitea-admin.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: git
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-admin-credentials
  data:
  - secretKey: username
    remoteRef:
      key: gitea/admin-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: gitea/admin-credentials
      property: password
