# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-secret-store.yaml
- external-secret-tls-wildcard-localtest-me.yaml
- external-secret-gitea-admin-credentials.yaml
- external-secret-db-credentials.yaml
- svc-vault-external.yaml
- ingress-vault-external.yaml
