apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-eventbus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    path: argo-events/eventbus
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: main
  destination:
    name: "in-cluster"
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
