apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    # helm search repo argo/argo-cd --versions | head
    targetRevision: 7.6.12
    helm:
      releaseName: argocd
      valueFiles:
      - $values/argocd/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: gitea-actions      # Specify one of:
    # targetRevision: main             # branch name
    # targetRevision: v1.0.0           # tag
    # targetRevision: 8c57e4d          # commit SHA (can be short)
    # targetRevision: HEAD             # latest commit
    ref: values
  destination:
    name: "in-cluster"
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
