apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-cluster-postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    # helm search repo cnpg/cloudnative-pg --versions | head
    targetRevision: 0.0.11
    helm:
      releaseName: cloudnativepg-cluster-postgresql
      # valueFiles:
      # - $values/cloudnativepg-postgresql/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: main
    ref: values
  destination:
    name: "in-cluster"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
