apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-pgsql-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    # helm search repo cnpg/cloudnative-pg --versions | head
    targetRevision: 0.22.1
    helm:
      releaseName: cnpg-pgsql-operator
      # valueFiles:
      # - $values/cloudnativepg-postgresql/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: main
    ref: values
  destination:
    name: "in-cluster"
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
