apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debug-shell
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    # repoURL: http://gitea-http.git.svc.cluster.local:3000/aruba-demo/debug-shell.git
    repoURL: https://github.com/kubernetista/debug-shell.git
    targetRevision: main
    path: kustomize
    # kustomize:
    #   namePrefix: debug-shell-
  destination:
    name: "in-cluster"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
