apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    # helm search repo external-secrets/external-secrets --versions | head
    targetRevision: 0.10.5
    helm:
      releaseName: external-secrets
      # valueFiles:
      # - $values/external-secrets/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: main
    ref: values
  destination:
    name: "in-cluster"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
