apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-uv
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: dev
    path: fastapi-uv/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
