apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-config
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: http://gitea-http.git.svc.cluster.local:3000/aruba-demo/debug-shell.git
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: HEAD
    path: k8s-config
    # kustomize:
    #   namePrefix: prefix-
  destination:
    name: "in-cluster"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
