apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetail
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://kubetail-org.github.io/helm-charts/
    chart: kubetail
    # helm search repo kubetail/kubetail --versions | head
    targetRevision: 0.8.4
    helm:
      releaseName: kubetail
      valueFiles:
      - $values/kubetail/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: gitea-actions      # Specify one of:
    # targetRevision: main             # branch name
    # targetRevision: v1.0.0           # tag
    # targetRevision: 8c57e4d          # commit SHA (can be short)
    # targetRevision: HEAD             # latest commit
    ref: values
  destination:
    name: "in-cluster"
    namespace: kubetail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
