apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-docs
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: http://gitea-http.git.svc.cluster.local:3000/aruba-demo/debug-shell.git
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: gitea-actions      # Specify one of:
    # targetRevision: main             # branch name
    # targetRevision: v1.0.0           # tag
    # targetRevision: 8c57e4d          # commit SHA (can be short)
    # targetRevision: HEAD             # latest commit
    path: nginx-docs
    # kustomize:
    #   namePrefix: debug-shell-
  destination:
    name: "in-cluster"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
