apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-docs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    # repoURL: http://gitea-http.git.svc.cluster.local:3000/aruba-demo/debug-shell.git
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: dev
    path: nginx-docs
  destination:
    name: "in-cluster"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
