apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-hello-aruba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.git.svc.cluster.local:3000/aruba-demo/python-hello-aruba.git
    targetRevision: main
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
