apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    # helm search repo traefik/traefik --versions | head
    targetRevision: 32.1.1
    helm:
      releaseName: traefik
      valueFiles:
      - $values/traefik/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: gitea-actions      # Specify one of:
    # targetRevision: main             # branch name
    # targetRevision: v1.0.0           # tag
    # targetRevision: 8c57e4d          # commit SHA (can be short)
    # targetRevision: HEAD             # latest commit
    ref: values
  destination:
    name: "in-cluster"
    namespace: traefik
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
