apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    # helm search repo traefik/traefik --versions | head
    targetRevision: 33.0.0
    helm:
      releaseName: traefik
      valueFiles:
      - $values/traefik/values.yaml
      # - values.yaml
  - repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: dev
    ref: values
  destination:
    name: "in-cluster"
    namespace: traefik
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
