apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-eso-test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: vault-eso-test-app
    repoURL: https://github.com/kubernetista/nuvola.git
    targetRevision: main
    # targetRevision: HEAD
  destination:
    name: "in-cluster"
    namespace: git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
