apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea-admin-secret
  namespace: git
data:
  ### aruba-demo - NeOzersChqN9fydl (aruba-demo@git.localhost)
  username: YXJ1YmEtZGVtbw==
  password:  TmVPemVyc0NocU45ZnlkbA==
  ### gitea_admin - r8sA8CPHD9!bt6d (default)
  # username: Z2l0ZWFfYWRtaW4=
  # password: cjhzQThDUEhEOSFidDZk
